FROM python:3.10-slim

EXPOSE 8000

WORKDIR /app
ENV PORT 8000
ENV HOST "0.0.0.0"
COPY ./src /app./src
COPY ./requirements.txt /app

RUN pip install -r requirements.txt

CMD ["uvicorn", "src.main:app", "--host=0.0.0.0", "--reload"]